### ISSUE TITLE
Buggy batch_processor.py code

### ISSUE THREAD

**Issue by rchikhi** [aws-samples/aws-batch-processing-job-repo#2]
Warning: the batch_processor.py code is overall of low quality. 
For example, running it without having the right environment variables set will cause `os.environ.get` to return `None`, making the next `logMessage` call crash.

https://github.com/aws-samples/aws-batch-processing-job-repo/blob/970ef16082e33f8c39c73a3c63979563972cb2e5/src/batch_processor.py#L132

Also, often `fileName` is confused with `productId` in logging.
And, argument parsing is broken, with `"-js"` being specified as a shorthand name for all three args.

**Comment by shivaramani** [comment]
Hello
Idea of the blog is to provide a sample concept to perform. In this example when the lambda function is provided (in cloudformation) it is set with sample environment variables.

The provided batch processing code is a working sample for a specific/example provided. In real world, depending on the use case the source could vary. 

https://github.com/aws-samples/aws-batch-processing-job-repo/blob/master/template/template.yaml#L218
